config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get  'stripe_log' => 'home#stripe_log'
  get  'german_words/load_from_file', to: 'german_words#load_from_file'
  put  'german_words/update_words', to: 'german_words#update_words'
	post 'vocab_tests/start', to: 'vocab_tests#start'
	post 'vocab_tests/complete_test', to: 'vocab_tests#complete_test'
  get  'pay', to: 'payments#new', as: 'payment'
  post 'pay' => 'payments#create', as: 'process_payment'
  get  'disclaimer', to: 'payments#disclaimer', as: 'disclaimer'
  post 'test_email', to: 'payments#signup_email', as: 'test_email'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :german_words
  resources :english_words

end

app/models/german_word.rb
class GermanWord < ActiveRecord::Base
	belongs_to :english_word
	has_many :plurals

	scope :nouns, -> { where("gender != ''") }

  def self.update_words(words)
    
    GermanWord.all.each do |de|
      # the dependent: :destroy was giving weird errors, so we
      # have to do this stupid shit.
      # we're loading them all back into the database anyways, whatevs.
      de.plurals.each { |p| p.destroy }
      de.destroy
    end

    words.keys.each do |word|
      words[word].each do |translation|
        en = EnglishWord.find_or_create_by(word: word, chapter: translation['chapter'])

        new_deutsch = en.german_words.create(
              book: translation['book'],
           chapter: translation['chapter'],
              word: translation['word'],
           article: translation['article'],
            gender: translation['gender']
        )

        if translation['plural']
          plural = translation['plural']
          
          new_deutsch.plurals.create(
                   article: plural['article'],
                      word: plural['word'],
                    gender: plural['gender'],
           english_word_id: en.id
          )
        end
      end
    end
  rescue Exception => e
    raise Exception, "Couldn't update words: #{e.message}"
  end
end

app/controllers/german_words_controller.rb
class GermanWordsController < ApplicationController
  before_action :set_german_word, only: [:show, :edit, :update, :destroy]

  # GET /german_words
  # GET /german_words.json
  def index
    @german_words = GermanWord.all
  end

  # GET /german_words/1
  # GET /german_words/1.json
  def show
  end

  # GET /german_words/new
  def new
    @german_word = GermanWord.new
  end

  # GET /german_words/1/edit
  def edit
  end

  # POST /german_words
  # POST /german_words.json
  def create
    @german_word = GermanWord.new(german_word_params)

    respond_to do |format|
      if @german_word.save
        format.html { redirect_to @german_word, notice: 'German word was successfully created.' }
        format.json { render :show, status: :created, location: @german_word }
      else
        format.html { render :new }
        format.json { render json: @german_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /german_words/1
  # PATCH/PUT /german_words/1.json
  def update
    respond_to do |format|
      if @german_word.update(german_word_params)
        format.html { redirect_to @german_word, notice: 'German word was successfully updated.' }
        format.json { render :show, status: :ok, location: @german_word }
      else
        format.html { render :edit }
        format.json { render json: @german_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /german_words/1
  # DELETE /german_words/1.json
  def destroy
    @german_word.destroy
    respond_to do |format|
      format.html { redirect_to german_words_url, notice: 'German word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def load_from_file
    @file_data = File.open("word_lists/de.json", "r").read
  end

  def update_words
    words = JSON.parse(params[:word_data])
    GermanWord.update_words(words)
    redirect_to :back, flash: { success: "Successfully updated words." }

  rescue Exception => e
    redirect_to :back, flash: { warning: e.message }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_german_word
      @german_word = GermanWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def german_word_params
      params.require(:german_word).permit(:word, :article, :gender, :english_word_id)
    end
end

app/helpers/german_words_helper.rb
module GermanWordsHelper
end

app/views/german_words/_form.html.erb
<%= form_for(@german_word) do |f| %>
  <% if @german_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@german_word.errors.count, "error") %> prohibited this german_word from being saved:</h2>

      <ul>
      <% @german_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :english_word_id %><br>
    <%= f.number_field :english_word_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/german_words/edit.html.erb
<h1>Editing german_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @german_word %> |
<%= link_to 'Back', german_words_path %>

app/views/german_words/index.html.erb
<h1>Listing german_words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Article</th>
      <th>Gender</th>
      <th>English word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @german_words.each do |german_word| %>
      <tr>
        <td><%= german_word.word %></td>
        <td><%= german_word.article %></td>
        <td><%= german_word.gender %></td>
        <td><%= german_word.english_word_id %></td>
        <td><%= link_to 'Show', german_word %></td>
        <td><%= link_to 'Edit', edit_german_word_path(german_word) %></td>
        <td><%= link_to 'Destroy', german_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New German word', new_german_word_path %>

app/views/german_words/load_from_file.html.haml
= stylesheet_link_tag params[:controller]

.field-container
  = form_tag("#{german_words_update_words_path}", method: :put) do
    = submit_tag "Update", class: "tag"
    %br
    = text_area_tag "word_data", @file_data, cols: "100", rows: "50", class: "tag"
 

app/views/german_words/new.html.erb
<h1>New german_word</h1>

<%= render 'form' %>

<%= link_to 'Back', german_words_path %>

app/views/german_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @german_word.word %>
</p>

<p>
  <strong>Article:</strong>
  <%= @german_word.article %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @german_word.gender %>
</p>

<p>
  <strong>English word:</strong>
  <%= @german_word.english_word_id %>
</p>

<%= link_to 'Edit', edit_german_word_path(@german_word) %> |
<%= link_to 'Back', german_words_path %>