config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get  'stripe_log' => 'home#stripe_log'
  get  'german_words/load_from_file', to: 'german_words#load_from_file'
  put  'german_words/update_words', to: 'german_words#update_words'
	post 'vocab_tests/start', to: 'vocab_tests#start'
	post 'vocab_tests/complete_test', to: 'vocab_tests#complete_test'
  get  'pay', to: 'payments#new', as: 'payment'
  post 'pay' => 'payments#create', as: 'process_payment'
  get  'disclaimer', to: 'payments#disclaimer', as: 'disclaimer'
  post 'test_email', to: 'payments#signup_email', as: 'test_email'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :german_words
  resources :english_words

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  def self.process_stripe_webhook(params)
    puts "Received a stripe webhook: \n#{params}"


    log_file = 'log/stripe_webhooks.txt'
    FileUtils.touch(log_file) unless File.exists?(log_file)
    
    puts "Writing to log file: #{log_file}"

    File.open('log/stripe_webhooks.txt', 'a') do |f|
      f.puts "\n"
      f.puts params.to_s
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!, except: [:disclaimer, :webhooks]

  respond_to :html

  def new
    @payment = Payment.new
    respond_with(@payment)
  end

  def create
    @amount = 500 # cents, not dollars :P
    @user = User.find_by(email: params[:stripeEmail])

    customer = if current_user.stripe_id
      Stripe::Customer.retrieve(current_user.stripe_id)
    else
      Stripe::Customer.create
    end
     
    customer.email = @user.email
    customer.card  = params[:stripeToken]
    customer.save

    @user.stripe_id = customer.id
    @user.save

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Vocabularist customer',
      :currency    => 'usd'
    )

    @user.activated = true
    @user.save

    Payment.create(
      email:      @user.email,
      stripe_id:  @user.stripe_id,
      status:     "success"
    )

    VocabularistMailer.signup_receipt(current_user).deliver!
    VocabularistMailer.signup_notification(current_user).deliver!

    redirect_to root_path, notice: "Your payment has been recieved and a receipt has been sent to your email. You're now free to use the rest of the site. Thank you!"

  rescue Stripe::CardError => e
    puts "Stripe card error: #{e.message}"
    e.backtrace.each { |m| "\tfrom #{m}" }
    redirect_to :back, flash: { alert: e.message }
  rescue Exception => e
    puts "Unexpected error in user signup: \n => #{e.message}"
    e.backtrace.each { |m| puts "\tfrom #{m}" }
    redirect_to :back, flash: { alert: "An unexpected error occurred processing your payment. Sorry about that." }
  end

  def disclaimer
    # hide the link from the footer.
    @disclaimer = true
  end

  def webooks
    # thank god stripe provided all this cool stuff.  i'm just wayyy too lazy fo dat.
    Payment.process_stripe_webhook(params)

    # Use Stripe's bindings...
  rescue Stripe::CardError => e
    # Since it's a decline, Stripe::CardError will be caught
    body = e.json_body
    err  = body[:error]

    puts "Status is: #{e.http_status}"
    puts "Type is: #{err[:type]}"
    puts "Code is: #{err[:code]}"
    # param is '' in this case
    puts "Param is: #{err[:param]}"
    puts "Message is: #{err[:message]}"
  rescue Stripe::RateLimitError => e
    # Too many requests made to the API too quickly
    puts "Stripe error: #{e.message}"
  rescue Stripe::InvalidRequestError => e
    # Invalid parameters were supplied to Stripe's API
    puts "Stripe error: #{e.message}"
  rescue Stripe::AuthenticationError => e
    # Authentication with Stripe's API failed
    # (maybe you changed API keys recently)
    puts "Stripe error: #{e.message}"
  rescue Stripe::APIConnectionError => e
    # Network communication with Stripe failed
    puts "Stripe error: #{e.message}"
  rescue Stripe::StripeError => e
    # Display a very generic error to the user, and maybe send
    # yourself an email
    puts "Stripe error: #{e.message}"
  rescue => e
    # Something else happened, completely unrelated to Stripe
  end

  def signup_email
    VocabularistMailer.signup_notification(current_user).deliver!
    redirect_to :back, flash: { notice: 'test email sent.' }
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:email, :stripe_id, :amount, :status)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
= form_for process_payment_path do |f|

  %script{  :src                => 'https://checkout.stripe.com/checkout.js',
            :class              => 'stripe-button',
            "data-email"        => "#{current_user.email}",
            "data-key"          => "#{Rails.configuration.stripe[:publishable_key]}",
            "data-amount"       => "500" }

app/views/payments/disclaimer.html.haml
.center
  .disclaimer
    %h2{ style: "padding: 30px; text-align: center" } DISCLAIMER & PRIVACY POLICY

    %p 
      payments are made through a secure API called Stripe. if you want to know more about this, you can visit their website
      = link_to 'here.', 'https://stripe.com/about', target: '_blank'

    %p i do not record any personal or credit card/billing information that may be relayed to/from this application in the midst of any transaction.
    
    %p 
      the source code to this application is available to the public.  you can find it 
      = link_to 'here.', 'https://github.com/elliotwesoff/Vocabularist', target: '_blank'

    %p the purchase of access to the entirety of this program is NON-REFUNDABLE, and is provided WITHOUT WARRANTY or any guarantee of functionality.

    %p i am not responsible for the learning (or lack thereof) that may occur during the use of this application.

    %p i am not responsible for the providing of false information (incorrect translations, spelling errors, etc.) that may be received by the user at any point in the use of this application (i use this program as well, so of course i want it to be as correct and accurate as possible.  please email me if you find any mistakes).

    %p i reserve the right to cancel any account at any time for any reason, with or without the user's consent.

    %p{ style: "text-align: center" } thank you for your understanding.

app/views/payments/new.html.haml
.center
  .payment
    %h3{ style: "margin: 0;" } payment details

    %table.payment-details
      %tr
        %td email:
        %td #{current_user.email}

      %tr
        %td amount:
        %td $5.00

      %tr
        %td.disclaimer{ colspan: '2', style: 'text-align: center;' }
          = link_to 'disclaimer', disclaimer_path, target: '_blank'

    = render 'form'