config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get  'stripe_log' => 'home#stripe_log'
  get  'german_words/load_from_file', to: 'german_words#load_from_file'
  put  'german_words/update_words', to: 'german_words#update_words'
	post 'vocab_tests/start', to: 'vocab_tests#start'
	post 'vocab_tests/complete_test', to: 'vocab_tests#complete_test'
  get  'pay', to: 'payments#new', as: 'payment'
  post 'pay' => 'payments#create', as: 'process_payment'
  get  'disclaimer', to: 'payments#disclaimer', as: 'disclaimer'
  post 'test_email', to: 'payments#signup_email', as: 'test_email'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :german_words
  resources :english_words

end

app/models/english_word.rb
class EnglishWord < ActiveRecord::Base
  has_many :german_words
  has_many :plurals

  def create_translations(params)
    #  this is probably real disgusting but i'm super fuckin burnt out n tird rn so
    #  don't fucking judge me bitch.  fuck off.

    if !params[:non_noun].blank?
      @non_noun = german_words.create(word: params[:non_noun], article: '', gender: '')
    else
      if !params[:singular].blank?
        params[:singular_art].blank? ? ms_art = 'der' : ms_art = params[:singular_art]
        @singular = german_words.create(word: params[:singular], article: ms_art, gender: 'singular')

        if !params[:plural].blank?
          params[:plural_art].blank? ? plural_art = 'die' : plural_art = params[:plural_art]
          @singular.plurals.create(word: params[:plural], article: plural_art, gender: 'plural')
        end
      end

      if !params[:fem_sing].blank?
        params[:fem_sing_art].blank? ? fs_art = 'die' : fs_art = params[:fem_sing_art]
        @fem_sing = german_words.create(word: params[:fem_sing], article: fs_art, gender: 'feminine singular')

        if !params[:fem_plur].blank?
          params[:fem_plur_art].blank? ? fp_art = 'die' : fp_art = params[:fem_plur_art]
          @fem_sing.plurals.create(word: params[:fem_plur], article: fp_art, gender: 'feminine plural')
        end
      end
    end

    { masc: @singular, fem: @fem_sing, neu: @neu_sing }
  end

  def self.get_json_words(words)
    word_hash = []

    words.each do |word|

      deutsches_wortes = word.german_words
      plurals = []

      deutsches_wortes.each do |wort|
        wort.plurals.each do |plural|
          plurals << plural
        end
      end

      word_hash << { english: word, german: deutsches_wortes, plurals: plurals }.to_json
    end

    word_hash
  end

  def self.get_test_words(params)
    # collect english words here...

    chapters = params[:chapters]
    words = []

    chapters.each do |ch|
      if params[:nouns_only]
        GermanWord.all.nouns.each { |wort| words << wort.english_word }
      else
        words << EnglishWord.where(chapter: ch.to_i) 
      end
    end

    words = words.flatten.uniq.shuffle!

    ques_limit = params[:question_limit]
    if !ques_limit.blank? && ques_limit.to_i > 0 && words.length > ques_limit.to_i
      words = words.drop(words.length - ques_limit.to_i)
    end

    return words
  end

  private

  def self.nuke!
    # FUCK YO COUCH CUHHH
    EnglishWord.destroy_all
    puts "destroyed all words."
  end
end

app/controllers/english_words_controller.rb
class EnglishWordsController < ApplicationController
  before_action :set_english_word, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

	def index
		@english_words = EnglishWord.all
	end

	def show
	end

	def new
		@english_word = EnglishWord.new
	end

	def edit
		@english_word = EnglishWord.find(params[:id])

		# take the old translations and store them so we don't
		# have to retype them into the form.
		@english_word.german_words.each do |wort|
			if wort.gender == 'singular'
				@singular = wort.word
			else
				@fem_sing = wort.word
			end

			wort.plurals.each do |plural|
				plural.gender == 'plural' ? @plural = plural.word : @fem_plur = plural.word
			end
		end

		# wipe out the old german words and plurals cause yo dumbass
		# messed them up before.
		@english_word.german_words.destroy_all
	end

	def create
		@english_word = EnglishWord.find_or_create_by(word: params[:english_word], chapter: params[:chapter].first)

		@english_word.create_translations(params)

		respond_to do |format|
			if @english_word.save
				format.html { redirect_to new_english_word_path, notice: "'#{@english_word.word}' and translations created successfully." }
				format.json { render :show, status: :created, location: @english_word }
			else
				format.html { redirect_to :back, alert: "there was a problem doing that..." }
				format.json { render json: @english_word.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @english_word.update(english_word_params)
				format.html { redirect_to @english_word, notice: 'English word was successfully updated.' }
				format.json { render :show, status: :ok, location: @english_word }
			else
				format.html { render :edit }
				format.json { render json: @english_word.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@english_word.destroy
		respond_to do |format|
			format.html { redirect_to english_words_url, notice: 'English word was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_english_word
		@english_word = EnglishWord.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def english_word_params
		params.require(:english_word).permit(:word, :chapter)
	end

end

app/helpers/english_words_helper.rb
module EnglishWordsHelper
end

app/views/english_words/_form.html.erb
<%= form_tag(controller: 'english_words', action: 'create', method: 'post', class: 'new_words') do |f| %>
  <% if @english_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@english_word.errors.count, "error") %> prohibited this english_word from being saved:</h2>

      <ul>
      <% @english_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

		<table class="add-word">
			<thead>
				<th>english:</th>
				<th>german:</th>
				<th>chapter:</th>
			</thead>

			<tbody>
				<tr>
					<td>
						<div class="field">
							<%= text_field_tag :english_word, @english_word.word if @english_word %>
						</div>
					</td>

					<td>

						<!-- non-nouns -->
						<div class="field">
							non-nouns:  
							<%= text_field_tag :non_noun %>
						</div>
						
						<!-- singular -->
						<div class="field">
							<%= label_tag :singular, 'sing.' %>
							<%= select_tag :singular_art, options_for_select(['', 'der', 'die', 'das']) %>
							<%= text_field_tag :singular, @singular %>
						</div>
						
						<!-- plural -->
						<div class="field" style="padding-bottom: 10px;">
							<%= label_tag :plural, 'plur.' %>
							<%= select_tag :plural_art, options_for_select(['', 'der', 'die', 'das']) %>
							<%= text_field_tag :plural, @plural %>
						</div>

						only for professions/people!
						<!-- feminine singular -->
						<div class="field" style="padding-top: 8px;">
							<%= label_tag :fem_sing, 'fem sing.' %>
							<%= select_tag :fem_sing_art, options_for_select(['', 'der', 'die', 'das']) %>
							<%= text_field_tag :fem_sing, @fem_sing %>
						</div>

						<!-- feminine plural -->
						<div class="field">
							<%= label_tag :fem_plur, 'fem plur.' %>
							<%= select_tag :fem_plur_art, options_for_select(['', 'der', 'die', 'das']) %>
							<%= text_field_tag :fem_plur, @fem_plur %>
						</div>

					</td>

					<td>
						<div class="field">
							<% chap_array = [] %>
							<% 11.times { |i| chap_array << i.to_s } %>
							<% chap_array.shift %>
							<%= select_tag :chapter, options_for_select(chap_array) %>
						</div>
					</td>
			</tr>
		</tbody>
	</table>

	<div class="actions">
		<%= submit_tag 'create' %>
	</div>

<% end %>

app/views/english_words/edit.html.erb
<h1>Editing english_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @english_word %> |
<%= link_to 'Back', english_words_path %>

app/views/english_words/index.html.erb
<%= link_to 'add word', new_english_word_path %><br />
<%= link_to 'load from file', german_words_load_from_file_path %><br />
<%= link_to 'send test email', test_email_path, method: :post %><br />


<div class='center'>
  <h2>word list (english to german)</h2>
</div>

<table class='word-list'>
  <thead>
    <tr>
      <th>english</th>
      <th>german</th>
			<th>plurals</th>
			<th>chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @english_words.each do |english_word| %>
			<tr> 
        <td><%= english_word.word %></td>
				<td>
					<% english_word.german_words.each do |german_word| %>
						<%= german_word.article %> <%= german_word.word %>,
					<% end %>
				</td>
				<td><%= english_word.german_words.map(&:plurals).flatten.map(&:word).join(', ') %></td>
        <td><%= english_word.chapter %></td>
				<td><%= link_to 'edit', edit_english_word_path(english_word) %></td>
        <td><%= link_to 'destroy', english_word, method: :delete, data: { confirm: 'are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/english_words/new.html.erb
<h3>new word!</h3>

<%= render 'form' %>

<%= link_to 'back', english_words_path %><br />
<%= link_to 'home', root_path %>

app/views/english_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @english_word.word %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @english_word.chapter %>
</p>

<%= link_to 'Edit', edit_english_word_path(@english_word) %> |
<%= link_to 'Back', english_words_path %>